import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createExample,changeParcel,summarize} from './model.js';
const $=id=>document.getElementById(id);
let parcels=createExample(),selected=10,mode='select',history=[],topView=false;
let scene,camera,renderer,controls,plots,selection;
const colors={grass:0xadc79d,park:0x9bb98e,road:0xb3c0c3,walk:0xe0e4dc,white:0xf4eee1,wood:0xa28061};
const materials=new Map();function mat(color){if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.9}));return materials.get(color);}
function box(parent,w,h,d,x,y,z,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function tree(parent,x,z,scale=1){const g=new THREE.Group();g.position.set(x,.2,z);g.scale.setScalar(scale);box(g,.19,1.5,.19,0,.75,0,0x9a8260);const foliage=new THREE.Mesh(new THREE.IcosahedronGeometry(.9,1),mat(0x73966c));foliage.scale.set(.85,1.25,.85);foliage.position.y=1.8;foliage.castShadow=true;g.add(foliage);parent.add(g);}
function bench(g,x,z){box(g,1.2,.12,.4,x,.52,z,colors.wood);box(g,1.2,.35,.09,x,.77,z+.2,colors.wood);[-.45,.45].forEach(dx=>box(g,.08,.4,.3,x+dx,.27,z,0x65726a));}
function roof(g,width,length,y,color){const shape=new THREE.Shape();shape.moveTo(-width/2,0);shape.lineTo(0,1.25);shape.lineTo(width/2,0);shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:length,bevelEnabled:false});const m=new THREE.Mesh(geo,mat(color));m.position.set(0,y,-length/2);m.castShadow=true;g.add(m);}
function house(g,p){const h=2.0+(p.id%3)*.35;const body=[0xede8d9,0xe6c7ab,0xe9ddc9,0xcbd6d5][p.id%4];box(g,3.1,h,3.05,0,h/2+.3,-.4,body);roof(g,3.55,3.6,h+.3,[0x9d7867,0x728d90,0xb38b74][p.id%3]);box(g,.38,1,.44,.83,h+.55,-.85,0xd9c7b2);box(g,.6,1.2,.08,.5,.9,1.16,0x877763);box(g,.85,.65,.08,-.8,1.5,1.17,0x647f86);box(g,.07,.68,.1,-.8,1.5,1.21,colors.white);box(g,.88,.07,.1,-.8,1.5,1.21,colors.white);box(g,.08,.7,.8,1.56,1.5,-.6,0x70868b);box(g,.12,.07,.83,1.59,1.5,-.6,colors.white);box(g,1,.07,2.1,.5,.27,2.15,colors.walk);box(g,1.4,.16,.6,.5,.37,1.5,0xd4d5c9);tree(g,-2.15,-2.1,.85);tree(g,2.2,1.6,.65);for(let i=0;i<p.residents;i++){const x=-1.65+i*.42;const person=new THREE.Mesh(new THREE.CapsuleGeometry(.11,.25,3,6),mat([0xd99567,0x547787,0xdab766,0x815f70][i]));person.position.set(x,.49,2.5);person.castShadow=true;g.add(person);const head=new THREE.Mesh(new THREE.SphereGeometry(.11,8,6),mat(0xe1c5a3));head.position.set(x,.8,2.5);g.add(head);} }
function park(g,p){box(g,1,.04,6,0,.24,0,0xd4d3b6);box(g,6,.04,.85,0,.25,.6,0xd4d3b6);[[-1.9,-1.6],[1.9,-1.9],[-2,2.1],[2,2]].forEach(([x,z],i)=>tree(g,x,z,.9+(i%2)*.25));bench(g,-1.7,.1);bench(g,1.7,1.1);const pond=new THREE.Mesh(new THREE.CylinderGeometry(.8,.9,.09,32),mat(0x81acb5));pond.position.set(1.7,.3,-.2);g.add(pond);}
function disposeGroup(g){g.traverse(o=>{if(o.geometry)o.geometry.dispose();});}
function renderParcels(){if(plots){scene.remove(plots);disposeGroup(plots);}plots=new THREE.Group();for(const p of parcels){const g=new THREE.Group();g.position.set(p.x,0,p.z);g.userData.parcelId=p.id;box(g,6.4,.25,6.4,0,.08,0,p.use==='park'?colors.park:colors.grass);if(p.use==='home')house(g,p);else if(p.use==='park')park(g,p);else {const line=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(5.5,.015,5.5)),new THREE.LineBasicMaterial({color:0xdde7d6}));line.position.y=.23;g.add(line);}plots.add(g);}scene.add(plots);updateSelection();}
function updateSelection(){const p=parcels.find(p=>p.id===selected);selection.position.set(p.x,.26,p.z);}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0xe7eff2);camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.1,250);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0xe7eff2);$('viewport').append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Maple Grove 3D map. Use the parcel selector to explore with a keyboard.');controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.maxPolarAngle=Math.PI/2.25;controls.minDistance=28;controls.maxDistance=180;controls.target.set(0,0,0);resetCamera();scene.add(new THREE.HemisphereLight(0xffffff,0xb4c3b0,2.6));const sun=new THREE.DirectionalLight(0xfff5e2,3.3);sun.position.set(-22,38,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30,near:1,far:100});sun.shadow.normalBias=.04;scene.add(sun);box(scene,36,.9,36,0,-.55,0,0xd7ddd3);box(scene,35.7,.12,35.7,0,-.06,0,colors.walk);for(let a=-16;a<=16;a+=8){box(scene,1.7,.04,34.7,a,.025,0,colors.road);box(scene,34.7,.045,1.7,0,.025,a,colors.road);for(let b=-14.5;b<16;b+=2){box(scene,.07,.015,.65,a,.055,b,0xe7eae3);box(scene,.65,.015,.07,b,.06,a,0xe7eae3);}}
// Street crossings and small cars make the connected street network legible.
for(const x of [-8,8])for(const z of [-8,8])for(let i=0;i<5;i++)box(scene,.16,.025,1.25,x-1.5+i*.3,.07,z,0xf0f0e8);
for(const [x,z,c,rot] of [[-8,3,0xe5ca85,0],[8,-4,0x7c99a7,0],[4,8,0xcc8b75,1],[-12,-8,0xf1eee0,1]]){const car=new THREE.Group();box(car,.65,.35,1.35,0,.25,0,c);box(car,.55,.25,.65,0,.52,0,0x69808a);car.position.set(x+.4,.05,z);car.rotation.y=rot*Math.PI/2;scene.add(car);}
const ringShape=new THREE.Shape();ringShape.moveTo(-3.35,-3.35);ringShape.lineTo(3.35,-3.35);ringShape.lineTo(3.35,3.35);ringShape.lineTo(-3.35,3.35);ringShape.closePath();const hole=new THREE.Path();hole.moveTo(-3.19,-3.19);hole.lineTo(-3.19,3.19);hole.lineTo(3.19,3.19);hole.lineTo(3.19,-3.19);hole.closePath();ringShape.holes.push(hole);selection=new THREE.Mesh(new THREE.ShapeGeometry(ringShape),new THREE.MeshBasicMaterial({color:0x3d786a,side:THREE.DoubleSide}));selection.rotation.x=-Math.PI/2;scene.add(selection);renderParcels();const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(plots.children,true)[0];if(hit){let obj=hit.object;while(obj&&!obj.userData.parcelId)obj=obj.parent;if(obj)select(obj.userData.parcelId,true);}});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});}
function resetCamera(){topView=false;camera.position.set(43,43,53);controls.target.set(0,0,0);if(innerWidth<700)camera.position.multiplyScalar(1.95);controls.update();}
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3400);}
function refresh(){const p=parcels.find(p=>p.id===selected),s=summarize(parcels);for(const k of ['homes','residents','parks'])$(k).textContent=s[k];$('occupancy').textContent=s.occupancy+'%';$('meter').style.width=s.occupancy+'%';$('parcel-id').textContent='P'+String(p.id).padStart(2,'0');$('parcel-name').textContent=p.use==='home'?'Maple House '+p.id:p.use==='park'?'Pocket Park '+p.id:'Room to grow';$('parcel-description').textContent={home:'A place to put down roots.',park:'A little green for everyone.',vacant:'Imagine what could be here.'}[p.use];$('attributes').innerHTML=`<dt>Land use</dt><dd>${{home:'Residential',park:'Green space',vacant:'Available'}[p.use]}</dd><dt>Street access</dt><dd>${p.streetAccess?'Connected':'Disconnected'}</dd><dt>${p.use==='home'?'Residents':'Parcel area'}</dt><dd>${p.use==='home'?p.residents+' / '+p.capacity:'400 m²'}</dd>`;$('rule-status').textContent=p.use==='home'?(p.residents===p.capacity?'✓ This home is at full capacity.':`✓ Space for ${p.capacity-p.residents} more resident${p.capacity-p.residents===1?'':'s'}.`):p.use==='park'?'✓ Shared green space for the neighborhood.':'✓ Connected and ready to develop.';$('move-in').disabled=p.use!=='home'||p.residents>=p.capacity;$('move-out').disabled=p.use!=='home'||!p.residents;$('undo').disabled=!history.length;$('parcel-select').value=p.id;if(selection)updateSelection();}
function select(id,apply=false){selected=Number(id);refresh();if(apply&&mode!=='select')act(mode);}
function act(action){try{const next=changeParcel(parcels,selected,action);history.push(parcels);parcels=next;renderParcels();refresh();toast({home:'A new home, ready for its first residents.',park:'A little more green in Maple Grove.',clear:'Parcel cleared and ready for something new.',in:'A resident has moved in.',out:'A resident has moved out.'}[action]);}catch(e){toast(e.message);}}
$('parcel-select').innerHTML=parcels.map(p=>`<option value="${p.id}">Parcel ${String(p.id).padStart(2,'0')}</option>`).join('');$('parcel-select').addEventListener('change',e=>select(e.target.value,true));
function setMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});$('hint').textContent={select:'Click a parcel to explore. Drag to orbit. Scroll to zoom.',home:'Choose an available parcel to build a home.',park:'Choose an available parcel to plant a pocket park.',clear:'Choose a park or an unoccupied home to clear.'}[mode];}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('move-in').onclick=()=>act('in');$('move-out').onclick=()=>act('out');$('undo').onclick=()=>{if(history.length){parcels=history.pop();renderParcels();refresh();toast('Last change undone.');}};$('reset').onclick=()=>$('reset-dialog').showModal();$('cancel-reset').onclick=()=>$('reset-dialog').close();$('confirm-reset').onclick=()=>{history.push(parcels);parcels=createExample();renderParcels();refresh();$('reset-dialog').close();toast('Maple Grove restored.');};$('help').onclick=()=>$('about').showModal();$('close-help').onclick=$('got-it').onclick=()=>$('about').close();$('home-view').onclick=resetCamera;function zoom(scale){const offset=camera.position.clone().sub(controls.target);offset.setLength(THREE.MathUtils.clamp(offset.length()*scale,controls.minDistance,controls.maxDistance));camera.position.copy(controls.target).add(offset);controls.update();}$('zoom-in').onclick=()=>zoom(.85);$('zoom-out').onclick=()=>zoom(1.18);$('view').onclick=()=>{topView=!topView;if(topView){camera.position.copy(controls.target).add(new THREE.Vector3(0,65,.01));controls.update();}else resetCamera();};window.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)||document.querySelector('dialog[open]'))return;if(e.ctrlKey||e.metaKey||e.altKey)return;if('1234'.includes(e.key))setMode(['select','home','park','clear'][Number(e.key)-1]);if(e.key==='Escape')setMode('select');});
try{init();refresh();}catch(e){console.error(e);const error=document.createElement('div');error.className='error';error.textContent='The 3D view could not start. Enable WebGL in your browser and reload this page.';document.body.append(error);}
